### PR TITLE
+ added link to user

### PR DESCRIPTION
**Pull request by FelixSFD**
Not sure, if it's actually working. I don't have a local copy of Bonfire. Feel free to improve my code

### CODE REVIEW

**Comment by Fortunate-MAN** [comment]
LGTM; thanks! I'll try using this later in the day, I'm kinda caught in another mess in Bonfire right now.

**Comment by Fortunate-MAN** [comment]
I'll go ahead and merge without actually testing it. Isn't that critical a change anyway!

**Review by double-fault — APPROVED** [review]

**Comment by Fortunate-MAN** [comment]
Oh, okay. It looks like I did overlook a thing. Next time, instead of using `+` to concatenate stuff in Ruby, use the other method: `#{variable_name}` which automatically converts the variable to a string. I'll just push the changes directly to master now.

**Comment by Fortunate-MAN** [comment]
[Finally got it working here](https://github.com/SOBotics/Bonfire/commit/4f53ad4253dbb3ccfce7e65aa441d5381d1f2d7e#diff-c7c9a522f39f5d8cd9b512cd928b2d14).

**Pull request merged**
